export const AGENT_LOGIN_REQUEST = "AGENT_LOGIN_REQUEST";
export const AGENT_LOGIN_SUCCESS = "AGENT_LOGIN_SUCCESS";
export const AGENT_LOGIN_FAIL = "AGENT_LOGIN_FAIL";
export const AGENT_LOGOUT = "AGENT_LOGOUT";

export const AGENT_REGISTER_REQUEST = "AGENT_REGISTER_REQUEST";
export const AGENT_REGISTER_SUCCESS = "AGENT_REGISTER_SUCCESS";
export const AGENT_REGISTER_FAIL = "AGENT_REGISTER_FAIL";

export const AGENT_UPDATE_REQUEST = "AGENT_UPDATE_REQUEST";
export const AGENT_UPDATE_SUCCESS = "AGENT_UPDATE_SUCCESS";
export const AGENT_UPDATE_FAIL = "AGENT_UPDATE_FAIL";
