export const ACCOUNTANT_LOGIN_REQUEST = "ACCOUNTANT_LOGIN_REQUEST";
export const ACCOUNTANT_LOGIN_SUCCESS = "ACCOUNTANT_LOGIN_SUCCESS";
export const ACCOUNTANT_LOGIN_FAIL = "ACCOUNTANT_LOGIN_FAIL";
export const ACCOUNTANT_LOGOUT = "ACCOUNTANT_LOGOUT";

export const ACCOUNTANT_REGISTER_REQUEST = "ACCOUNTANT_REGISTER_REQUEST";
export const ACCOUNTANT_REGISTER_SUCCESS = "ACCOUNTANT_REGISTER_SUCCESS";
export const ACCOUNTANT_REGISTER_FAIL = "ACCOUNTANT_REGISTER_FAIL";

export const ACCOUNTANT_UPDATE_REQUEST = "ACCOUNTANT_UPDATE_REQUEST";
export const ACCOUNTANT_UPDATE_SUCCESS = "ACCOUNTANT_UPDATE_SUCCESS";
export const ACCOUNTANT_UPDATE_FAIL = "ACCOUNTANT_UPDATE_FAIL";
