export const CSR_LOGIN_REQUEST = "CSR_LOGIN_REQUEST";
export const CSR_LOGIN_SUCCESS = "CSR_LOGIN_SUCCESS";
export const CSR_LOGIN_FAIL = "CSR_LOGIN_FAIL";
export const CSR_LOGOUT = "CSR_LOGOUT";

export const CSR_REGISTER_REQUEST = "CSR_REGISTER_REQUEST";
export const CSR_REGISTER_SUCCESS = "CSR_REGISTER_SUCCESS";
export const CSR_REGISTER_FAIL = "CSR_REGISTER_FAIL";

export const CSR_UPDATE_REQUEST = "CSR_UPDATE_REQUEST";
export const CSR_UPDATE_SUCCESS = "CSR_UPDATE_SUCCESS";
export const CSR_UPDATE_FAIL = "CSR_UPDATE_FAIL";
