export const FRANCHISE_LOGIN_REQUEST = "FRANCHISE_LOGIN_REQUEST";
export const FRANCHISE_LOGIN_SUCCESS = "FRANCHISE_LOGIN_SUCCESS";
export const FRANCHISE_LOGIN_FAIL = "FRANCHISE_LOGIN_FAIL";
export const FRANCHISE_LOGOUT = "FRANCHISE_LOGOUT";

export const FRANCHISE_REGISTER_REQUEST = "FRANCHISE_REGISTER_REQUEST";
export const FRANCHISE_REGISTER_SUCCESS = "FRANCHISE_REGISTER_SUCCESS";
export const FRANCHISE_REGISTER_FAIL = "FRANCHISE_REGISTER_FAIL";

export const FRANCHISE_UPDATE_REQUEST = "FRANCHISE_UPDATE_REQUEST";
export const FRANCHISE_UPDATE_SUCCESS = "FRANCHISE_UPDATE_SUCCESS";
export const FRANCHISE_UPDATE_FAIL = "FRANCHISE_UPDATE_FAIL";
