export const HANDLER_LOGIN_REQUEST = "HANDLER_LOGIN_REQUEST";
export const HANDLER_LOGIN_SUCCESS = "HANDLER_LOGIN_SUCCESS";
export const HANDLER_LOGIN_FAIL = "HANDLER_LOGIN_FAIL";
export const HANDLER_LOGOUT = "HANDLER_LOGOUT";

export const HANDLER_REGISTER_REQUEST = "HANDLER_REGISTER_REQUEST";
export const HANDLER_REGISTER_SUCCESS = "HANDLER_REGISTER_SUCCESS";
export const HANDLER_REGISTER_FAIL = "HANDLER_REGISTER_FAIL";

export const HANDLER_UPDATE_REQUEST = "HANDLER_UPDATE_REQUEST";
export const HANDLER_UPDATE_SUCCESS = "HANDLER_UPDATE_SUCCESS";
export const HANDLER_UPDATE_FAIL = "HANDLER_UPDATE_FAIL";
